<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>online-shop</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <modules>

        <module>CommonEvents</module>
        <module>OrderService</module>
        <module>ProductService</module>
        <module>PaymentService</module>
        <module>CartService</module>
        <module>AuthService</module>
        <module>UserService</module>
        <module>ApiGateway</module>
        <module>OrderOrchestratorService</module>
        <module>NotificationService</module>

    </modules>

</project>