spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**, /uploads
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/api/products/**, /api/categories/**

        - id: cart-service
          uri: http://cart-service:8084
          predicates:
            - Path=/api/carts/**

        - id: order-service
          uri: http://order-service:8085
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/api/payments/**

      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://127.0.0.1:5500"
                  - "http://localhost:5500"
                  - "http://localhost:5173"
                  - "http://127.0.0.1:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true


  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

    properties:
      spring.json.add.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: user
    password: password

  data:
    redis:
      host: redis
      port: 6379
      password: ""
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  tracing:
    sampling:
      probability: 1.0   # 100% запросов

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

app:
  public:
    key:
      path: classpath:keys/public.pem

rate-limit:

  default-config:
    capacity: 100
    refill-rate: 1

  endpoints:

    "[/api/auth/login]":
      capacity: 5
      refill-rate: 0.1

    "[/api/auth/refresh]":
      capacity: 3
      refill-rate: 0.1

    "[/api/auth/logout]":
      capacity: 3
      refill-rate: 0.1

    "[/api/auth/register]":
      capacity: 3
      refill-rate: 0.1

    "[/api/products]":
      capacity: 300
      refill-rate: 5

    "[/api/orders]":
      capacity: 100
      refill-rate: 1

    "[/api/cart]":
      capacity: 150
      refill-rate: 2

    "[/api/profile]":
      capacity: 60
      refill-rate: 1

    "[/api/admin]":
      capacity: 1000
      refill-rate: 20

