spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/auth/${segment}

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/users/**, /uploads
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}, /api/v1/images/users/**

        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**, /api/v1/flash-sales/**, /api/v1/images/products/**

        - id: cart-service
          uri: http://cart-service:8080
          predicates:
            - Path=/api/v1/carts/**

        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path=/api/v1/payments/**




  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

    properties:
      spring.json.add.type.headers: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

app:
  public:
    key:
      path: ${JWT_PUBLIC_KEY}

rate-limit:

  default-config:
    capacity: 100
    refill-rate: 1

  endpoints:

    "[/api/auth/login]":
      capacity: 5
      refill-rate: 0.1

    "[/api/auth/refresh]":
      capacity: 3
      refill-rate: 0.1

    "[/api/auth/logout]":
      capacity: 3
      refill-rate: 0.1

    "[/api/auth/register]":
      capacity: 3
      refill-rate: 0.1

    "[/api/products]":
      capacity: 300
      refill-rate: 5

    "[/api/orders]":
      capacity: 100
      refill-rate: 1

    "[/api/cart]":
      capacity: 150
      refill-rate: 2

    "[/api/profile]":
      capacity: 60
      refill-rate: 1

    "[/api/admin]":
      capacity: 1000
      refill-rate: 20

