spring.application.name=UserService

# JPA
spring.jpa.properties.hibernate.default_schema=user_service
spring.jpa.hibernate.ddl-auto=update

# JWT
app.public.key.path=${JWT_PUBLIC_KEY}

#Url
services.order.url=http://order-service:8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cache=TRACE

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=user-consumers-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# MinIO
minio.bucket=avatars

# Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]