# Security
logging.level.org.springframework.security=DEBUG

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
logging.level.org.springframework.cache=TRACE

# MinIO
minio.url=http://minio:9000
