spring.application.name=NotificationService

#JPA
spring.jpa.properties.hibernate.default_schema=notification_service
spring.jpa.hibernate.ddl-auto=update

#Keys
app.public.key.path=${JWT_PUBLIC_KEY}

#Kafka
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-consumers-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]

#Telegram
telegram.bot.chat-id=1248111540
