spring.application.name=OrderService

#JPA
spring.jpa.properties.hibernate.default_schema=order_service
spring.jpa.hibernate.ddl-auto=update

#Keys
app.public.key.path=${JWT_PUBLIC_KEY}

#Url
services.cart.url=http://cart-service:8080
services.payment.url=http://cart-service:8080
services.product.url=http://cart-service:8080

#Kafka
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=orders-consumers-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]

# Retry
resilience4j.retry.instances.cart-service.max-attempts=3
resilience4j.retry.instances.cart-service.wait-duration=1s

# Circuit Breaker
resilience4j.circuitbreaker.instances.cart-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.cart-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.cart-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cart-service.wait-duration-in-open-state=30s

# Product Retry
resilience4j.retry.instances.product-service.max-attempts=3
resilience4j.retry.instances.product-service.wait-duration=1s

# Product Circuit Breaker
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=30s