spring.application.name=OrderService

server.port=8085

spring.datasource.url=jdbc:postgresql://postgres:5432/shop_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.properties.hibernate.default_schema=order_service
spring.jpa.hibernate.ddl-auto=update

app.public.key.path=classpath:public.pem

#Log
logging.level.org.springframework.security=DEBUG

#Kafka
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=product-consumers-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode=manual

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Redis

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.jedis.pool.max-idle=8

logging.level.org.springframework.cache=TRACE

#Prometheus
management.endpoints.web.exposure.include=prometheus,health,info

management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0

logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]

# Retry
resilience4j.retry.instances.cart-service.max-attempts=3
resilience4j.retry.instances.cart-service.wait-duration=1s

# Circuit Breaker
resilience4j.circuitbreaker.instances.cart-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.cart-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.cart-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cart-service.wait-duration-in-open-state=30s

# Product Retry
resilience4j.retry.instances.product-service.max-attempts=3
resilience4j.retry.instances.product-service.wait-duration=1s

# Product Circuit Breaker
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=30s