spring.application.name=CartService

server.port=8084

spring.datasource.url=jdbc:postgresql://postgres:5432/shop_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update